name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: true
        
    - uses: astral-sh/setup-uv@v2
    - run: uv build
    - name: Publish to PyPI
      run: uv publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}